integration/go-http-client/client_test.go, integration/go-http-server/main.go
This PR addresses the following issues:
1. use `golang/protobuf/jsonpub` as marshaler/unmarshaler - the default `encoding/json` cannot handle camelCase json generated by Java server.
2. update the dependency of google cloud-trace format since it is moved to another package (https://github.com/census-instrumentation/opencensus-go/pull/555).
Though this change is tested locally, it is my first time writing in Golang. Please pardon me if I make any mistakes :)
=> Update google format dependency and use protobuf json marshaler.

integration/build.gradle, integration/src/main/java/io/opencensus/interop/TestUtils.java, integration/src/main/java/io/opencensus/interop/grpc/GrpcInteropTestClient.java, integration/src/main/java/io/opencensus/interop/grpc/GrpcInteropTestServer.java, integration/src/main/java/io/opencensus/interop/grpc/GrpcInteropTestUtils.java, integration/src/main/java/io/opencensus/interop/http/HttpInteropTestClient.java, integration/src/main/java/io/opencensus/interop/http/HttpInteropTestServer.java, integration/src/main/java/io/opencensus/interop/http/HttpInteropTestUtils.java, integration/src/main/java/io/opencensus/interop/http/netty/NettyUtils.java, integration/src/main/java/io/opencensus/interop/http/netty/OpenCensusClientInboundOutboundHandler.java, integration/src/main/java/io/opencensus/interop/http/netty/OpenCensusServerInboundOutboundHandler.java
* extract common test logic into `TestUtils`
* place propagation logic into `io.opencensus.interop.http.netty.*`, which will be later moved into a separate artifact `opencensus-contrib-http-netty`.
* main test logic is in `HttpInteropTestServer` and `HttpInteropTestClient`.
=> Add Java HTTP interop test.

integration/Makefile, integration/java/build.gradle
Our goal should be to test the latest snapshot of the github repo, rather than the released maven jars. Add a step to clone and install latest OpenCensus Java version in Makefile, and update Java interop build dependencies to be consistent with v0.13.0-SNAPSHOT.
=>  Install latest OpenCensus Java version in Makefile and update dependency

integration/java/grpc/io/opencensus/interop/grpc/GrpcInteropTestClient.java, integration/java/util/io/opencensus/interop/util/TestUtils.java
Temporarily fix the interop test failure between Java and Go gRPC tests because gRPC-Go doesn't propagate method tag. In the long term, we may want to make all tags non-propagate by default in Java.
/cc @dinooliva
=> Do not verify method tag in gRPC interop test.

integration/go/grpc/client/interop_test.go, integration/go/grpc/server/main.go, integration/go/http/server/main.go
This repository was moved from
`census-instrumentation/opencensus-experiments`
to
`census-ecosystem/opencensus-experiments`
but the rename wasn't applied to the code inside. I just
noticed this while running the interop tests.
=> integration/go: fix import paths that got changed after rename

java/log_correlation/stackdriver/java_util_logging/README.md, java/log_correlation/stackdriver/java_util_logging/build.gradle, java/log_correlation/stackdriver/logback/README.md, java/log_correlation/stackdriver/logback/build.gradle
This commit also updates the name of the trace sampled field for
https://github.com/census-instrumentation/opencensus-java/pull/1418.
=> Update Stackdriver log correlation demos for opencensus-java 0.16.0.

java/log_correlation/stackdriver/java_util_logging/build.gradle, java/log_correlation/stackdriver/logback/build.gradle
This commit upgrades google-cloud-logging to 1.44.0 and upgrades
google-cloud-logging-logback to 0.62.0-alpha.
=> Upgrade Stackdriver log correlation dependencies on google-cloud-logging.

java/log_correlation/log4j2/build.gradle, java/log_correlation/stackdriver/java_util_logging/build.gradle, java/log_correlation/stackdriver/logback/build.gradle
opencensus-java 0.16.1 has a fix for
https://github.com/census-instrumentation/opencensus-java/issues/1436, which
affected the Log4j log correlation demo.
=> Log correlation demos: Upgrade opencensus-java to 0.16.1.

java/log_correlation/log4j2/README.md, java/log_correlation/log4j2/src/main/resources/log4j2.xml
Formatting the trace ID in the logging configuration is no longer necessary now
that fluent-plugin-google-cloud formats the trace ID
(https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/260).
=> Remove trace ID formatting from Log4j log correlation demo logging config.

interoptest/src/testcoordinator/registrationservice/doc.go, interoptest/src/testcoordinator/registrationservice/registration_handler.go, interoptest/src/testcoordinator/registrationservice/registration_receiver.go
Fixes https://github.com/census-ecosystem/opencensus-experiments/issues/82.
For now the test coordinator just stores the registered services in a map.
=> interoptest/testcoordinator: start implementing registration service.

interoptest/src/pythonservice/flaskserver.py, interoptest/src/pythonservice/grpcserver.py, interoptest/src/pythonservice/service.py
This diff replaces the logging exporter in each service with the agent exporter, and replaces the gcloud format propagator in the flask service with a W3C tracecontext propagator.
This is largely untested except to check that the right exporter/propagator is being set. We may have to configure the exporter for the agent used in the interop test.
=> Export to OC agent in python services

interoptest/interoperability_test_pb2.py, interoptest/interoperability_test_pb2_grpc.py, interoptest/requirements.txt, interoptest/run.py
Adds a basic script to kick off a test and print the results. We may want to package this differently -- e.g. as an installable python package or inside another docker container -- to get rid of these symlinks and so that we don't need `grpcio` installed on the system running the tests.
=> Add script to run tests

interoptest/src/ocagent/config.yaml
According to https://github.com/census-ecosystem/opencensus-experiments/tree/master/interoptest#test-coordinator-tasks:
> Listens on Port 10001 for trace/stats export from OC Agent.
=> interoptest: update ocagent exporter endpoint.

interoptest/src/pythonservice/flaskserver.py, interoptest/src/pythonservice/grpcserver.py
Use `0.0.0.0` in place of `localhost` in the python flask service.
=> Use external host address in flask service

interoptest/src/pythonservice/service.py
Use `/test/request` instead of `/test/request/`.
=> Lose trailing slash in flask route

interoptest/src/testcoordinator/interoptestservice/interop_test_service.go, interoptest/src/testcoordinator/testexecutionservice/request_sender.go
Updates https://github.com/census-ecosystem/opencensus-experiments/issues/133.
TODO:
1. load test suites from txt files.
2. verify span attributes once they're added.
=> interoptest/tc: updates interop test service.

interoptest/src/pythonservice/flaskserver.py, interoptest/src/pythonservice/grpcserver.py
Following #156, adds the request ID as a span attribute in both python services.
=> Add reqID to spans in python

interoptest/README.md
Looks like in all the three languages (Go, Python and Node) we named this attribute "reqId", but in the spec it's "req.id".
See https://github.com/census-ecosystem/opencensus-experiments/pull/165/files#diff-52c50f72a64a669802062f7b2a245210R84, https://github.com/census-ecosystem/opencensus-experiments/pull/163/files#diff-144f321644819dda858f64caf79690aeR33 and https://github.com/census-ecosystem/opencensus-experiments/pull/156/files#diff-58a54f6d89e9a5c8d24f0e01926c7644R57.
=> interoptest: update reqId key.

interoptest/src/testcoordinator/receiver/sink.go
Go `append()` is not like Java `addAll()`.
=> interoptest/tc: fix a bug in TestCoordinatorSink.

java/log_correlation/log4j2/src/main/resources/log4j2.xml
This commit sets the new sampling decision field that is recognized by the
Stackdriver Logging agent, "logging.googleapis.com/traceSampled", in the Log4j
log correlation demo.  The sampling decision field was added in
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/297.
=> Use Stackdriver special field to set sampling decision in log correlation demo.
